googleapis/java-storage-nio

- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageConfigurationTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileAttributeViewTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageLateInitializationTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStoragePathTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannelTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadFileChannelTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteChannelTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteFileChannelTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/UnixPathTest.java
> chore: remove usage of deprecated ExpectedException JUnit rule

- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
> samples: fix install-without-bom version

- pom.xml
> build: update annotationprocessorpaths to include auto-value-annotation

- google-cloud-nio/pom.xml
> chore: remove duplicate dependencies

- .gitignore
- google-cloud-nio-examples/pom.xml
- google-cloud-nio-retrofit/pom.xml
- google-cloud-nio/pom.xml
- pom.xml
> feat(deps): adopt flatten plugin and google-cloud-shared-dependencies

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannel.java
> chore: remove unchecked call warning

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
> chore: remove extra conditional from FakeStorageRpc#list

- .readme-partials.yaml
- .repo-metadata.json
- README.md
- samples/install-without-bom/pom.xml
- samples/snapshot/pom.xml
- samples/snippets/pom.xml
> chore: fix README generation

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java
> doc: Document CloudStoragePath

- .kokoro/build.sh
- synth.py
> chore: add retries for build.sh for unit tests

- google-cloud-nio/pom.xml
> chore(deps): Remove google-cloud-core (tests) dep version

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
> chore: update FakeStorageRpc documentation

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
> fix: change CloudStorageFileSystemProvider to throw a FileAlreadyExistsException if copy receives a 412

- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
> test: disable requester pays tests

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/testing/LocalStorageHelperTest.java
> fix: Check generation for nullability before incrementing it

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java
- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java
- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageUtil.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemTest.java
Fixes https://github.com/googleapis/java-storage-nio/issues/1218 ☕️
> feat: Store bucket name in URI authority

- .github/workflows/unmanaged_dependency_check.yaml
- renovate.json
> chore: add unmanaged dependency check

- google-cloud-nio/pom.xml
- renovate.json
See https://github.com/googleapis/java-storage-nio/pull/897 and https://github.com/googleapis/java-storage-nio/pull/992 for history
> build: revert maven-shade-plugin to v3.2.4

- .github/workflows/samples.yaml
Fixes #<issue_number_goes_here> ☕️
> chore: change samples check to run with java 11

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageConfiguration.java
- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java
- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
- google-cloud-nio/src/main/resources/META-INF/native-image/com/google/cloud/google-cloud-nio/native-image.properties
Fixes #1464 ☕️
- Default constructor of `CloudStorageFileSystemProvider` references only `CloudStorageConfiguration`
> fix: Minimize initialize at buildtime

- google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java
- google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpcTest.java
Add a test to validate the fix.
Fixes #1526
> fix: update FakeStorageRpc to be able to handle incremental resumable upload puts

- .github/workflows/ci.yaml
Fixes #<issue_number_goes_here> ☕️
> chore: add JDK 25 to ci
