googleapis/java-storage-nio

README.md, google-cloud-nio-examples/pom.xml, google-cloud-nio-examples/src/main/java/com/google/cloud/examples/nio/CountBytes.java, google-cloud-nio-examples/src/main/java/com/google/cloud/examples/nio/ParallelCountBytes.java, google-cloud-nio-examples/src/main/java/com/google/cloud/examples/nio/Stat.java, pom.xml
The example links were broken as a result of the repo split.
This PR copies the NIO examples from googleapis/google-cloud-java/google-cloud-examples/
to this repo, and fixes the links. It makes more sense to have the library and the related examples together in the same repository.
=> samples: migrate examples from google-cloud-examples

google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadFileChannelTest.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteFileChannelTest.java
=> chore: remove usege of deprecated assertThat of JUnit

google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannelTest.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageWriteChannelTest.java
=> chore: remove usage of deprecated matcher and verifyZeroInteractions of mockito

README.md
=> fix: point to correct api documentation

pom.xml
Fix dependencies for google-cloud-storage 1.109.1.
Need to cut release with these dependencies then can ping libraries bom release.
=> dep: update dependencies

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java, pom.xml
=> test: update FakeStorageRpc to extend StorageRpcTestBase

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemTest.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
=> feat: update cloudstorageconfiguration to improve copy accross cross-bucket performance

CHANGELOG.md
Version number is currently off by one, I fixed the release tag, updating the changelog as well to reflect that
=> chore: realign version number

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java, pom.xml
=> fix: implement writeWithResponse in FakeStorageRpc

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
=> fix: FakeStorageRpc#list to filtering the files by bucket and prefix

google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/NIOTest.java
Make sure we find the provider and it recognizes paths as expected.
These tests don't actually connect to any Google Cloud Storage
bucket.
cf. https://github.com/googleapis/google-cloud-java/pull/7082
=> test: test that Java picks up the NIO provider

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageIsDirectoryTest.java
=> fix: use projectId from CloudStorageConfig

google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/NIOTest.java
When starting a test, there is a `gs://` uri which is referenced before any unit test level configuration of CloudStorageFileSystemProvider. If NIOTest runs as the first test in the JVM, CloudStorageFileSystemProvider will initialize internally using all default options (which are production endpoints).
This fix ensures that before the `gs://` uri is resolved in the NIOTests that LocalStorageHelper is configured rather than defaults.
=> fix(test): update NIOTest to ensure LocalStorageHelper is used

google-cloud-nio/pom.xml, pom.xml
* update dependency com.google.cloud:google-cloud-shared-dependencies to v2.0.0
* update dependency com.google.cloud:google-cloud-core:test to v2.0.2
* update dependency com.google.cloud:google-cloud-storage to v2.0.0
Replaces #628, #632, #638
=> deps: update google-cloud-* libraries to v2

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
=> fix: Requester pays to check reason and fallback to error message validation

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java
Fixes a NullPointerException introduced in #841 which occured when trying
to check the the requesterPays status of a file while authenticated with an
invalid service account.
Refs: #849, #841
Fixes #849 ☕️
=> fix: prevent NPE when checking requester pays status

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageConfiguration.java, google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStoragePath.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Fixes a crash that occurred when autoDetectRequesterPays is set and
a Files.exists() call is made on a file that doesn't exist.
Refs: #856
Fixes #856 ☕️
=> fix: prevent crash when checking if a missing file exists #856

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
Fixes a NullPointerException when creating a Path object with a bucket
that doesn't exist. This only occurred when autoDetectRequesterPays = true.
Refs: #857
Fixes #857☕️
=> fix: Prevent NPE when bucket doesn't exist #857

google-cloud-nio/src/main/resources/META-INF/native-image/com/google/cloud/google-cloud-nio/native-image.properties
Using META-INF/services with Native Image compilation causes the `FileSystemProvider` class to be initialized at build time. This causes `com.google.cloud.storage.contrib.nio.CloudStorageFileSystemProvider` and a couple of unexpected classes that are referenced to also be initialized at build time.
=> fix(java): initialize classes at build-time to fix Native Image compilation

google-cloud-nio/pom.xml, owlbot.py, renovate.json
Due to a bug in maven shade plugin 3.3.0, compile dependencies got stripped from `google-cloud-nio:shaded`. This bug only affects artifacts where shadedArtifactAttached=true.
Related: https://github.com/googleapis/java-bigtable-hbase/pull/3600
Reference: https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-419
=> fix(build): revert maven-shade-plugin 3.3.0

.readme-partials.yaml, README.md, google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageConfiguration.java
=> docs: Update documentation to be clearer on pseudo-directory pitfalls

renovate.json
maven-shade-plugin does not yet fix
https://issues.apache.org/jira/projects/MSHADE/issues/MSHADE-419
=> chore: exclude maven-shade-plugin v3.4.0

renovate.json
Port of https://github.com/googleapis/synthtool/pull/1594 due to renovate.json being excluded from template in this repo.
=> chore: exclude requirements.txt file from renovate-bot

.kokoro/build.sh
The build script additions were excluded from this PR https://github.com/googleapis/java-storage-nio/pull/742.
=> chore: restore missing native image configs

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
=> feat: FileSystemProvider::readAttributes for basic and gcs views

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
=> FileSystemProvider::checkAccess fails on '/' with StorageException

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystem.java, google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemTest.java
This is the follow up patch after #1066 to add fake posix support in FileSystemProvider::readAttributes.
Important to note is that the values returned in this patch are all fixed and fake.
The main goal of this patch is to have minimal support for the posix attributes because some existing libraries fail if a filesystem does not support this at all. By adding faked support many of these libraries become usable in combination with cloud storage with minimal effort.
I expect that after this some may want to add a more accurate mapping of the attributes.
Fixes #1062 ☕️
=> feat: FileSystemProvider::readAttributes faked posix support

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/SeekableByteChannelPrefetcher.java
In file: SeekableByteChannelPrefetcher.java, class: `SeekableByteChannelPrefetcher`, there is a method fetch in which there is a potential Null pointer dereference. This may throw an unexpected null pointer exception which, if unhandled, may crash the program. 
In line 345 of SeekableByteChannelPrefetcher.java, we have 
WorkUnit candidate=fetching;
Here fetching may be null. There is already hint at that in the null check in line 342. If `fetching` is null, we would have gone into the call to `ensureFetching`. Now this part is a grey area. The method is suggesting that it will ensure that `fetching` will have a value, but apparently, there may be ways to return from the function without updating the value of `fetching`. An example is line 309. 
Then again, In line 359, the variable …
=> fix: Add protection against a possible null dereference issue

.kokoro/presubmit/graalvm-native-17.cfg, .kokoro/presubmit/graalvm-native.cfg, owlbot.py, pom.xml, renovate.json
Notable Changes:
1) Use `gcr.io/cloud-devrel-public-resources/graalvm_sdk_platform*` docker images for Kokoro GraalVM tests  instead of `gcr.io/cloud-devrel-kokoro-resources/graalvm*`.
2) Use `com.google.cloud:sdk-platform-java-config` as the parent which inherits configs from `java-shared-config` and hosts the `google-cloud-shared-dependencies` version under the `google-cloud-shared-dependencies.version` property.  This artifact is versioned to be the same as google-cloud-shared-dependencies.
3) Adjust renovate-bot settings to update docker images when a new version of `sdk-platform-java-config` is on Maven Central.
Example renovate-bot update PR in google-cloud-java: https://github.com/googleapis/google-cloud-java/pull/10290
=> chore: use sdk-platform-java-config to consolidate build configs

pom.xml
Follow-up to https://github.com/googleapis/java-storage-nio/pull/1357/. Closes #1366
=> chore: rely on shared-dependencies version from sdk-platform-java-config

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java
Currently, when CloudStorageFileSystemProvider#getFileAttributeView is invoked with a class it doesn't recognize it throws an UnsupportedOperationException. The javadocs for FileSystemProvider, however specify that #getFileAttributeView[1] return null if the attribute view type is not available.
This change updates the behavior of CloudStorageFileSystemProvider#getFileAttributeView to return null rather than throw an exception.
Fixes #1424
[1] https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html#getFileAttributeView(java.nio.file.Path,java.lang.Class,java.nio.file.LinkOption...)
=> fix: update CloudStorageFileSystemProvider#getFileAttributeView to return null rather than throw UnsupportedOperationException

.github/workflows/unmanaged_dependency_check.yaml, google-cloud-nio-bom/pom.xml, pom.xml
Fixes https://github.com/googleapis/sdk-platform-java/issues/3063.
The unmanaged dependency check works with a BOM that lists the
artifacts published from a repository. The bom-path argument of
the workflow has been wrongly specified to the root pom.xml.
This pull request fixes the wrong argument by introducing the
google-cloud-nio-bom.
This is the same fix we applied for java-bigquery. In fact, this
change copies the google-cloud-bigquery-bom and modified the
artifact name and version.
With this pull request, I confirmed the unmanaged dependency check passes locally:
```
suztomo@suztomo2:~/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check$ mvn exec:java -Dexec.args="../pom.xml /usr/local/google/home/suztomo/java-storage-nio/google-cloud-nio-bom/pom.xml"
[INFO] …
```
=> ci: google-cloud-nio-bom to list the artifact in from this repo

.github/CODEOWNERS, .repo-metadata.json
clean up outdated cloud-storage-dpe team
=> chore: set gcs-sdk-team as storage codeowners

google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java, google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProviderTest.java, google-cloud-nio/src/test/java/com/google/cloud/storage/contrib/nio/it/ITGcsNio.java
=> feat: implement CloudStorageFileSystemProvider.move method using the moveBlob API
